// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByefD3jA3aMy14qknpNkzEj0SB8W71Y4Y',
    appId: '1:588371357859:web:c1a26c924215f9242b8f16',
    messagingSenderId: '588371357859',
    projectId: 'mis-lab3-59b0d',
    authDomain: 'mis-lab3-59b0d.firebaseapp.com',
    storageBucket: 'mis-lab3-59b0d.appspot.com',
    measurementId: 'G-HW49R1ELSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyxJ_suQ8kvl7ACORwAtyZV4aSTsxZsOw',
    appId: '1:588371357859:android:a2f46aa6a9980a302b8f16',
    messagingSenderId: '588371357859',
    projectId: 'mis-lab3-59b0d',
    storageBucket: 'mis-lab3-59b0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCortoeC3kLfzlcJcz3L6oezrmMnkFhWgU',
    appId: '1:588371357859:ios:8e7cd5c01689b0ad2b8f16',
    messagingSenderId: '588371357859',
    projectId: 'mis-lab3-59b0d',
    storageBucket: 'mis-lab3-59b0d.appspot.com',
    iosClientId:
        '588371357859-diuu20oaecmaqtnoug3n1n6u724vu1ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCortoeC3kLfzlcJcz3L6oezrmMnkFhWgU',
    appId: '1:588371357859:ios:f097e2c1f20f5c6e2b8f16',
    messagingSenderId: '588371357859',
    projectId: 'mis-lab3-59b0d',
    storageBucket: 'mis-lab3-59b0d.appspot.com',
    iosClientId:
        '588371357859-o3k1nse5gkuuqbvnc4oqfktr1dc5kd4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab3.RunnerTests',
  );
}
